---
title: "AirHealth Data Bridges project"
---

{{< include /_common.qmd >}}

The AirHealth Data Bridges project (<https://doi.org/10.47486/PS022>) ran from 2021 to 2023, with the aim to expand CARDAT datasets and tools. This project received co-investment support from the ARDC.

The AirHealth Data Bridges project built a new Integrated National Air Pollution and Health Data platform. The data platform builds on the successful collaborations between many Australian academics who are working together as part of the Centre for Air pollution, energy and health Research (CAR) (now the [Centre for Safe Air][csa-home]) and the [Healthy Environments And Lives (HEAL)][heal-home] National Research Network, which both received funding from the National Health and Medical Research Council (NHMRC). The data platform extends the CAR Data and Analysis Technology ([CARDAT][cardat-home]) project. 

Partners include Curtin University, the NSW Department of Planning and Environment, EPA Victoria, the Australian Institute of Health and Welfare, Monash University, the University of Queensland and the University of Sydney.

Read more about this project at <https://cardat.github.io/air-health-data-bridges/>.