---
title: "Accessing CARDAT resources"
aliases: 
    - "/acknowledgements.html"
---

## CARDAT Platform Acknowledgement

When publishing work that has used resources (datasets or tools) from the CARDAT platform, please include an acknowledgement statement such as: 

>This research was undertaken with the assistance of resources from the Clean Air Research Data and Analysis Tools (CARDAT) platform (https://cardat.github.io). CARDAT is supported by The Centre for Safe Air (https://safeair.org.au/), which is funded by the National Health and Medical Research Council (2015584) and the Australian Research Data Commons (ARDC) AirHealth Data Bridges project (https://doi.org/10.47486/PS022), and the WHO Collaborating Centre for Climate Change and Health Impact Assessment.

Please ensure your usage falls within the bounds of the relevant licence and conditions of use set by the data owner. Where possible, cite the software and/or datasets that you have used in your output.

## Data repository

CARDAT holds data at varying levels of restriction and access, ranging from publicly available, Creative Commons-licensed datasets to commercial datasets restricted to one or two users.

Data is generally divided into the following categories.

**Environment General datasets**

This subset of CARDAT datasets does not require particular permission from the data owner for access and is open to all Centre for Safe Air (CSA) members. Those outside of CSA may be granted access if nominated by a Chief or Associate Investigator.

**Restricted datasets**

Access to restricted datasets is given on a case-by-case basis, subject to the conditions and licensing imposed by the data owner. A request may be submitted via the data access request form.

**Public datasets**

A small subset of datasets, including the National Air Pollution Monitor Database (NAPMD), is open to academics and students for non-commercial research purposes.
